server:
  port: ${REST_SERVICE_PORT:8181}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:userok}
    password: ${POSTGRES_PASSWORD:bestuser}
  jpa:
    generate-ddl: true

salt: ${SALT:test}